/*
 * Assignment1.c
 *
 * Created: 10/03/2025 15:21:05
 * Author : lican
 */ 

#define F_CPU 14745600UL
#define COMPARE_VALUE 0x7080


#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>

#define d0 0xc0
#define d1 0xf9
#define d2 0xa4
#define d3 0xb0
#define d4 0x99
#define d5 0x92
#define d6 0x82
#define d7 0xf8
#define d8 0x80
#define d9 0x90

static const uint8_t digitmap[10] = {0xc0, 0xf9, 0xa4, 0xb0, 0x99, 0x92, 0x82, 0xf8, 0x80, 0x90};
volatile uint8_t SEGF = 0; //flag

void timer_init() //TIMER1 16bits
{
	unsigned int value = COMPARE_VALUE;
	OCR1AH = (value >> 8) & 0xFF; // setting the value of the comparator
	OCR1AL = value & 0xFF;
	
	TCCR1B |= (1 << WGM12) | (1 << CS12); // CTC mode + prescalar 256 (CS12=1 CS11=0 CS10=0)
	TCCR1A &= ~(1 << WGM11) & ~(1 << WGM10); // CTC mode
}
void init_digit()
{
	DDRA = 0x7F; // set port A as output
	PORTA = 0x00; //initially all off
}
void display_digit(uint8_t digit)
{
	PORTA = digit;
}
void clear_digit()
{
	PORTA = 0x00; //initially all off
}

void interrupt_init()
{
	sei(); //enable ATMEGA global interrupts
	TIMSK |= (1 << OCIE1A); //enable the interrupt signaling for TIMER1 that's being used
	
	//cli(); disable ATMEGA global interrupts
}
ISR(TIMER1_COMPA_vect) //signal generated by the interrupt
{
	SEGF = 1;
}

int main(void)
{	
	init_digit();
	timer_init();
	interrupt_init();
    while (1) 
    {
		if(SEGF == 1)
		{
			static int i = 0;
			i = (i + 1) % 10;
			display_digit(digitmap[i]);
			SEGF = 0;
		}
    }
}

