/*
 * Assignment1.c
 *
 * Created: 10/03/2025 15:21:05
 * Author : lican
 */ 

#define F_CPU 14745600UL

#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include "./Timer-Header/timer.h"

void led_init()
{
	DDRB |= (1 << PB0); // setup led (output)
	PORTB &= ~(1 << PB0); //initially off
}
void led_toggle()
{
	PORTB ^= (1 << PB0);
}
void interrupt_init()
{
	sei(); //enable ATMEGA global interrupts
	TIMSK |= (1 << OCIE1A); //enable the interupt signaling for TIMER1 that's being used
	
	//cli(); disable ATMEGA global interrupts
}
ISR(TIMER1_COMPA_vect) //signal generated by the interrupt
{
	LEDF = 1;
}


int main(void)
{	
	led_init();
	timer_init();
	interrupt_init();
    while (1) 
    {
		if(LEDF == 1)
		{
			led_toggle();
			LEDF = 0;
		}
    }
}

